### ISSUE TITLE
Example sketches no longer compile

### ISSUE THREAD

**Issue by driverblock** [adafruit/Adafruit_LSM303DLHC#11]
Example sketches throw compile errors:
In file included from magsensor.pde:3:
/Users/ricklesniak/Documents/Arduino/libraries/Adafruit_LSM303DLHC/Adafruit_LSM303_U.h:163: error: conflicting return type specified for 'virtual bool Adafruit_LSM303_Accel_Unified::getEvent(sensors_event_t*)'
/Users/ricklesniak/Documents/Arduino/libraries/Adafruit_Sensor/Adafruit_Sensor.h:146: error:   overriding 'virtual void Adafruit_Sensor::getEvent(sensors_event_t*)'
/Users/ricklesniak/Documents/Arduino/libraries/Adafruit_LSM303DLHC/Adafruit_LSM303_U.h:185: error: conflicting return type specified for 'virtual bool Adafruit_LSM303_Mag_Unified::getEvent(sensors_event_t*)'
/Users/ricklesniak/Documents/Arduino/libraries/Adafruit_Sensor/Adafruit_Sensor.h:146: error:   overriding 'virtual void Adafruit_Sensor::getEvent(sensors_event_t*)'

**Comment by microbuilder** [comment]
You need to get the latest version of the libraries from Github (Adafruit_Sensor as well as the LSM303 library).
