### ISSUE TITLE
No need to wait for Wire.available().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_LSM303DLHC#12]
This line is a few times in the code : "while (Wire.available() < 6);".
But it is not correct to wait after Wire.requestFrom().

And a Wire.requestFrom() should not be followed by a Wire.endTransmission().

Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1, 2 and 5.

**Comment by siddacious** [comment]
Thanks for pointing this out. This library has been replaced by the libraries below and will be archived.
https://github.com/adafruit/Adafruit_LSM303_Accel and
https://github.com/adafruit/Adafruit_LSM303DLH_Mag

Your feedback has been addressed by switching to use of the [Adafruit_BusIO](https://github.com/adafruit/Adafruit_BusIO

The I2C implementation under the hood does not have the issues you pointed out. 

https://github.com/adafruit/Adafruit_BusIO/blob/master/Adafruit_I2CDevice.cpp
