### ISSUE TITLE
Wrong assumption at the test

### ISSUE THREAD

**Issue by LinuxLiveWire** [adafruit/Adafruit_LSM303DLHC#13]
I am talking about the following lines - [GitHub](https://github.com/adafruit/Adafruit_LSM303DLHC/blob/master/Adafruit_LSM303_U.cpp#L351)

``` c
// LSM303DLHC has no WHOAMI register so read CRA_REG_M to check
// the default value (0b00010000/0x10)
uint8_t reg1_a = read8(LSM303_ADDRESS_MAG, LSM303_REGISTER_MAG_CRA_REG_M);
if (reg1_a != 0x10)
{
  return false;
}
```

On my device (Adafruit 9-DOF IMU) all work perfect, until a new value is not set in the register CRA_REG_M different from LSM303_MAGRATE_15 (means by Adafruit_LSM303_Mag_Unified::setMagRate method);
It seems (and i verified it) that the IMU remembers the last values stored in the register, and during the next boot will not pass this test. Personally, I have found how to get around this problem in my sketch, but I think that the assumptions made in this test is incorrect and may come as a surprise to many library users.

**Comment by siddacious** [comment]
Thanks for pointing this out. This library has been replaced by the libraries below and will be archived.
https://github.com/adafruit/Adafruit_LSM303_Accel and
https://github.com/adafruit/Adafruit_LSM303DLH_Mag

Your feedback has been addressed here by checking the values of known fixed registers as suggested by another user:
https://github.com/adafruit/Adafruit_LSM303DLH_Mag/blob/master/Adafruit_LSM303DLH_Mag.cpp#L115

Cheers!
