### ISSUE TITLE
Bad method Adafruit_LSM303_Mag_Unified::setMagRate(lsm303MagRate rate)

### ISSUE THREAD

**Issue by PBernalPolo** [adafruit/Adafruit_LSM303DLHC#17]
In [Adafruit_LSM303DLHC/Adafruit_LSM303_U.cpp](https://github.com/adafruit/Adafruit_LSM303DLHC/blob/master/Adafruit_LSM303_U.cpp),
```
void Adafruit_LSM303_Mag_Unified::setMagRate(lsm303MagRate rate)
{
  byte reg_m = ((byte)rate & 0x07) << 2;
  write8(LSM303_ADDRESS_MAG, LSM303_REGISTER_MAG_CRA_REG_M, reg_m);
}
```
you are writing in the register `LSM303_REGISTER_MAG_CRA_REG_M`.
In [Adafruit_LSM303DLHC/Adafruit_LSM303_U.h](https://github.com/adafruit/Adafruit_LSM303DLHC/blob/master/Adafruit_LSM303_U.h),
```
typedef enum
    {
      LSM303_REGISTER_MAG_CRA_REG_M             = 0x00,
      LSM303_REGISTER_MAG_CRB_REG_M             = 0x01,
      LSM303_REGISTER_MAG_MR_REG_M              = 0x02,
      LSM303_REGISTER_MAG_OUT_X_H_M             = 0x03,
      LSM303_REGISTER_MAG_OUT_X_L_M             = 0x04,
      LSM303_REGISTER_MAG_OUT_Z_H_M             = 0x05,
      LSM303_REGISTER_MAG_OUT_Z_L_M             = 0x06,
      LSM303_REGISTER_MAG_OUT_Y_H_M             = 0x07,
      LSM303_REGISTER_MAG_OUT_Y_L_M             = 0x08,
      LSM303_REGISTER_MAG_SR_REG_Mg             = 0x09,
      LSM303_REGISTER_MAG_IRA_REG_M             = 0x0A,
      LSM303_REGISTER_MAG_IRB_REG_M             = 0x0B,
      LSM303_REGISTER_MAG_IRC_REG_M             = 0x0C,
      LSM303_REGISTER_MAG_TEMP_OUT_H_M          = 0x31,
      LSM303_REGISTER_MAG_TEMP_OUT_L_M          = 0x32
    } lsm303MagRegisters_t;
```
Searching in the [datasheet](https://www.sparkfun.com/datasheets/Sensors/Magneto/LSM303%20Datasheet.pdf), in "8 Register mapping", page 27, we can read that one should not write in the registers 00-0F because they are reserved. It also reads at the end of the table "Registers marked as Reserved must not be changed. Writing to these registers may cause permanent damage to the device.".

Conclusion: The device of those who have used this code, like me, may have been permanently damaged.

**Comment by microbuilder** [comment]
Thanks for filing an issue, but that datasheet is for the LSM303DLH not the LSM303DLHC which is a different IC. The right one is available [here](http://www.st.com/content/ccc/resource/technical/document/datasheet/56/ec/ac/de/28/21/4d/48/DM00027543.pdf/files/DM00027543.pdf/jcr:content/translations/en.DM00027543.pdf).

You can see the relevant section for this register below (with no ominous destruction implied):

<img width="326" alt="screen shot 2017-10-09 at 18 24 07" src="https://user-images.githubusercontent.com/181073/31348211-295bc29e-ad1f-11e7-8445-d5ba01d805de.png">

This seems correct to me since we are leaving the reserved bits as 0 as indicated, and only setting the DO0..2 bits, which can be written to.

**Comment by microbuilder** [comment]
You may also be looking at the ACCELEROMETER registers, whereas the register you are pointing out is for the MAGNETOMETER. There are two different sensors inside this IC, each with their own register sets. The 00..1F range is reserved for the ACCEL sensor, yes, but definitely not for the MAG sensor where many important user registers are located.

This may be what confused you as well (ACCEL regs shown below):

<img width="318" alt="screen shot 2017-10-09 at 18 28 48" src="https://user-images.githubusercontent.com/181073/31348430-e891b0e2-ad1f-11e7-8188-e60f8dcf79e8.png">

**Comment by PBernalPolo** [comment]
You are right. Sorry. I added that line of code, and for some reason my device stopped working.
Now it is working again. I should have double checked. I will do it the next time.
