### ISSUE TITLE
No mechanism for setting sensor update rate & other control registers

### ISSUE THREAD

**Issue by logos-electromechanical** [adafruit/Adafruit_LSM303DLHC#3]
Would the maintainers be open to a patch doing the following things to the Adafruit_LSM303_Accel_Unified & Adafruit_LSM303_Mag_Unified classes?

-- Add setUpdateRate()/getUpdateRate() functions to set and return the current update rate, including an additional enum type for the allowed values.

-- Add setRegister()/getRegister() functions to set and get arbitrary registers. 

Ideally, I'd add interrupt support and functions for most if not all of the registers, but I don't have the bandwidth to write that big an extension right now.

**Comment by georgeharker** [comment]
See https://github.com/adafruit/Adafruit_LSM303DLHC/pull/9 for the rate part

**Comment by microbuilder** [comment]
Merged in https://github.com/adafruit/Adafruit_LSM303DLHC/pull/9
